### ISSUE TITLE
Expandable groups should have a top-border when a header is absent

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-expandables#45]
When an expandable group has a header there is a horizontal rule between the header and the expandable items. However, when a header isn't used the horizontal rule is gone:

With header:
![screen shot 2015-04-03 at 12 34 00 pm](https://cloud.githubusercontent.com/assets/704760/6985127/e250a866-d9fd-11e4-8e97-9059e4dd54db.png)

Without header:
![screen shot 2015-04-03 at 12 34 10 pm](https://cloud.githubusercontent.com/assets/704760/6985128/e5d2dfc2-d9fd-11e4-9ae1-a1fe8ffcc5b3.png)

The expandable group should keep the horizontal rule at the top whether a header is present or not, so that it looks like:
![screen shot 2015-04-03 at 12 36 46 pm](https://cloud.githubusercontent.com/assets/704760/6985143/1ee08cb0-d9fe-11e4-8f59-6ae6fce0d5e1.png)

**Comment by anselmbradford** [comment]
This should be a matter of:
1. Removing https://github.com/cfpb/cf-expandables/blob/gh-pages/src/less/cf-expandables.less#L680
2. Adding a `:first-child` pseudoselector:
   
   ``` less
   .expandable-group .expandable:first-child {
       border-top: 1px solid @expandable-group-divider;
   }
   ```

EDIT: It's not this simple, b/c the expandable-group header is a `div`, so `first-child` won't be applied when  the group header (`.expandable-group_header`) is present.

**Comment by anselmbradford** [comment]
Another approach is to add a wrapper div to the `.expandables` and create a new class:

``` html
<div class="expandable-group">
        <div class="expandable-group_header">...</div>
        <div class="expandable-group_items">
             <div class="expandable expandable__padded">...</div>
             <div class="expandable expandable__padded">...</div>
             ...
        </div>
</div>
```

``` less
.expandable-group_items .expandable:first-child {
    border-top: 1px solid @expandable-group-divider;
}
```

EDIT: See https://github.com/cfpb/cfgov-refresh/pull/455

**Comment by himedlooff** [comment]
Another approach would be something like

``` css
.expandable-group .expandable {
  border-top: 1px solid something;
  border-bottom: 1px solid something;
}
.expandable-group .expandable + .expandable {
  margin-top: -1px;
}
```
